service: bandego

plugins:
  - serverless-offline

provider:
  name: aws
  region: us-east-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:GetItem
          Resource:
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-data-table"
            - "arn:aws:dynamodb:${aws:region}:${aws:accountId}:table/${self:service}-data-table/index/*"
  ecr:
    images:
      appimage:
        path: ./
        # platform: linux/amd64 # Se precisar especificar a arquitetura

functions:
  NewImage:
    image:
      name: appimage
    events:
      - http:
          path: /newImage
          method: post
    environment:
      DATA_TABLE: ${self:service}-data-table

resources:
  Resources:
    DataTable:
      Type: AWS::DynamoDB::Table
      # ...
    ImageBucket:
      Type: AWS::S3::Bucket
      # ...

package:
  individually: true
  patterns:
    - '!node_modules/**'
    - '!.venv/**'
    - '!__pycache__/**'
    - '!.pytest_cache/**'
    - '!layer/**'